# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme            : "Palvef/Palve-blog@main"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title                    : "Palve"
title_separator          : "-"
# subtitle                 : "blog"
name                     : "Palve"
description              : "The little personal site for Palve"
url                      : "https://blog.palve.moe"
baseurl                  : ""
repository               : "Palvef/Palve-blog"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/favicon.png"
masthead_title           : "Palve" # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
enable_copy_code_button  : # true, false (default)
copyright                : # "copyright" name, defaults to site.title
copyright_url            : # "copyright" URL, defaults to site.url
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : "palvef" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia, google
lunr:
  search_within_pages    : # true, false (default)
algolia:
  application_id         : "KWFF82AV02" # YOUR_APPLICATION_ID
  index_name             : "palve_blog_articles" # YOUR_INDEX_NAME
  search_only_api_key    : "35961cf079cd7e38ef0bca4ed5e20342" # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : Palve # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-Y7KVPN8R2K"
    anonymize_ip         : false # true, false (default)


# Site Author
author:
  name             : "Palve"
  avatar           : "/assets/avatar.png" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "System administrator, Developer."
  location         : null
  email            : null
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:i@palve.moe"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://palve.moe"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Palvef"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "Telegram Channel"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/Palvefs"
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Palvef"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  #smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax
  parse_block_html: false # true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      #start_line: 1


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  quiet_deps: true


# Outputting
source_url: "https://github.com/Pavlef/Palve-blog"
index_url: /
permalink: /:year/:month/:title/
timezone: "Etc/UTC" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%b %-d, %Y" 


# Pagination with jekyll-paginate
paginate: null # amount of posts to show
# paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
paginate: null
#paginate_path: "/blog/:num/"
pagination:
  enabled: true
  per_page: 8
  permalink: "/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    layouts: ['autopages.html']
    title: 'Category: :cat'
    permalink: '/category/:cat'
  collections:
    layouts: ['autopages.html']
    title: 'Collection: :coll'
    permalink: '/collection/:coll'
  tags:
    layouts: ['autopages.html']
    title: 'Tag: :tag'
    permalink: '/tag/:tag'

collections:
  home:
    output: true
    permalink: "/:path/"
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - year
    # - categories
    # - tags
  layout: archive-taxonomy
  layouts: {}
  permalinks:
    year: /year/:year/
    category: /category/:name/
    tag: /tag/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: home
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      show_date: true
      related: true
      toc: true
      #toc_label: "On this page"
  - scope:
      path: ""
      type: home
    values:
      #classes: wide
      no_pagination: true
  - scope:
      path: ""
      type: share
    values:
      #classes: wide
      related: true
      sidebar:
        nav: share
  - scope:
      path: ""
      type: pages
    values:
      author_profile: false
      comments: false
      related: false
  - scope:
      path: ""
      type: tag
    values: &tag-defaults
      comments: false
      related: false
  - scope:
      path: ""
      type: category
    values:
      <<: *tag-defaults
